"""create_core_dataforge_tables

Revision ID: c1e37e3f22f3
Revises: 60a5be0e671d
Create Date: 2026-09-22 15:08:02.185458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c1e37e3f22f3'
down_revision: Union[str, None] = '60a5be0e671d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS citext')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_datasets_active_owner_name', 'datasets', ['owner_id', sa.text('lower(name)')], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_user_revoked_expires', 'refresh_tokens', ['user_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPLOADING', 'UPLOADED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='dataset_version_status'), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dataset_versions_dataset_created', 'dataset_versions', ['dataset_id', 'created_at'], unique=False)
    op.create_index('uq_dataset_versions_dataset_number', 'dataset_versions', ['dataset_id', 'version_number'], unique=True)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='analysis_status'), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_analysis_runs_version_type_fingerprint', 'analysis_runs', ['version_id', 'analysis_type', 'input_fingerprint'], unique=True)
    op.create_table('dataset_columns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('inferred_type', sa.Enum('INTEGER', 'DECIMAL', 'BOOLEAN', 'DATETIME', 'TEXT', 'UNKNOWN', name='column_type'), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_dataset_columns_version_name', 'dataset_columns', ['version_id', 'normalized_name'], unique=True)
    op.create_index('uq_dataset_columns_version_ordinal', 'dataset_columns', ['version_id', 'ordinal'], unique=True)
    op.create_table('dataset_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('storage_provider', sa.String(length=64), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=32), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'RETRYING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_jobs_status_queued', 'processing_jobs', ['status', 'queued_at'], unique=False)
    op.create_index('uq_processing_jobs_version_type_key', 'processing_jobs', ['version_id', 'job_type', 'idempotency_key'], unique=True)
    op.create_index('uq_processing_jobs_active_version_type', 'processing_jobs', ['version_id', 'job_type'], unique=True, postgresql_where="status NOT IN ('COMPLETED', 'FAILED', 'CANCELLED')")
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_row_count', sa.BigInteger(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('profile_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id')
    )
    op.create_table('quality_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'WARN', 'FAIL', name='quality_status'), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('affected_rows', sa.BigInteger(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_quality_results_version_check_time', 'quality_results', ['version_id', 'check_type', 'computed_at'], unique=True)
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_query_hash', sa.String(length=64), nullable=False),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUCCEEDED', 'REJECTED', 'FAILED', name='query_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_history_user_created', 'query_history', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_query_history_version_created', 'query_history', ['version_id', 'created_at'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('result_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('column_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('column_id', sa.UUID(), nullable=False),
    sa.Column('null_count', sa.BigInteger(), nullable=False),
    sa.Column('null_fraction', sa.Numeric(precision=8, scale=7), nullable=False),
    sa.Column('unique_count', sa.BigInteger(), nullable=True),
    sa.Column('uniqueness_ratio', sa.Numeric(precision=8, scale=7), nullable=True),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('numeric_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categorical_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datetime_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['dataset_columns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('column_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_statistics')
    op.drop_table('analysis_results')
    op.drop_index('ix_query_history_version_created', table_name='query_history')
    op.drop_index('ix_query_history_user_created', table_name='query_history')
    op.drop_table('query_history')
    op.drop_index('uq_quality_results_version_check_time', table_name='quality_results')
    op.drop_table('quality_results')
    op.drop_table('profiles')
    op.drop_index('uq_processing_jobs_active_version_type', table_name='processing_jobs')
    op.drop_index('uq_processing_jobs_version_type_key', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_status_queued', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('dataset_files')
    op.drop_index('uq_dataset_columns_version_ordinal', table_name='dataset_columns')
    op.drop_index('uq_dataset_columns_version_name', table_name='dataset_columns')
    op.drop_table('dataset_columns')
    op.drop_index('uq_analysis_runs_version_type_fingerprint', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('uq_dataset_versions_dataset_number', table_name='dataset_versions')
    op.drop_index('ix_dataset_versions_dataset_created', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index('ix_refresh_tokens_user_revoked_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_datasets_active_owner_name', table_name='datasets', postgresql_where='deleted_at IS NULL')
    op.drop_table('datasets')
    op.drop_table('users')
    op.execute('DROP EXTENSION IF EXISTS citext')
    # ### end Alembic commands ###
